version: "3.8"

services:
  flask:
    build: .
    expose:
      - "5001"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  nginx:
    image: nginx:latest
    ports:
      - "5001:5001"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask

volumes:
  redis-data:
